name: Update GitHub Stats

on:
  push:
    branches:
      - main  # or your default branch
  schedule:
    - cron: '0 0 * * *'  # Runs daily, you can adjust the frequency

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get GitHub stats
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        # Set the username and URL for stats
        USERNAME="Caniscent"
        STATS_URL="https://github-readme-stats-eight-theta.vercel.app/api?username=${USERNAME}&show_icons=true&theme=radical&count_private=true&include_all_commits=true&access_token=${{ secrets.GH_TOKEN }}"
        LANGS_URL="https://github-readme-stats-eight-theta.vercel.app/api/top-langs/?username=${USERNAME}&layout=compact&langs_count=10&theme=radical&count_private=true&include_all_commits=true&access_token=${{ secrets.GH_TOKEN }}"

        # Update the README with the dynamic stats URLs
        sed -i "s|https://github-readme-stats-eight-theta.vercel.app/api?username=Caniscent|${STATS_URL}|" README.md
        sed -i "s|https://github-readme-stats-eight-theta.vercel.app/api/top-langs/?username=Caniscent|${LANGS_URL}|" README.md

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add README.md
        git commit -m "Update GitHub stats"
        git push
